### ISSUE TITLE
Example app can't connect to drone

### ISSUE THREAD

**Issue by JoshLikesBeer** [YUNEEC/Yuneec-SDK-Android-Example#31]
I have the ST16 controller and the Typhoon H drone.

I built an APK from this sample app and installed it on the ST16. I ensured that the ST16 is connected to the drone's WiFi. I see these errors repeating in the log when I start the sample app.

```
DroneLink: Error: no device found.
DroneLink: Remote IP unknown
DroneLink: send fail
DroneLink: Error: Send message failed
DroneLink: Error: Param to get drone type failed.
DroneLink: connection send error (511)
```

I don't know what's causing these errors, and haven't been able to find any answers online.

The one panel in the app that allows me to download files from the drone works (mostly -- I can see the files, but I have the same issue that julianoes reported yesterday), but none of the other panels work for me.

Any ideas what I'm doing wrong? Is there a step I missed?

Thanks.

**Comment by JoshLikesBeer** [comment]
In the ConnectionListenter.registerConnectionListener() method, the call to Connection.addListener() returns Connection.Result.ResultID.SUCCESS, but neither the connectionListener.onDiscoverCallback() nor the onTimeoutCallback() methods are ever called.

I tried moving the call to Connection.addListener(connectionListenter) to be before the call to Connection.addListener(), but it didn't make a difference.

**Comment by Sushma7785** [comment]
Hi @JoshLikesBeer. The current SDK only supports Typhoon H520. It is not compatible with Typhoon H. 
https://www.yuneec.com/en_GB/camera-drones/h520/overview.html
