### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by luk77** [YUNEEC/Yuneec-SDK-Android-Example#51]
Hi,
I am not able to build this project in Android Studio.
Few months ago I tested it (on other machine) and it worked, but now I am getting the message:
"Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.github.YUNEEC:Yuneec-SDK-Android:v0.14.5-1."

![image](https://user-images.githubusercontent.com/6962576/84147069-0fae8f00-aa5d-11ea-8e87-84d743cad5aa.png)

Currently I am using Android Studio 4.0 on Windows 10.

I also have some issues trying to register as a developer on: https://developer.yuneec.com/user/register
I am constantly getting message: "CAPTCHA error: Please ensure that captcha challenge has beeen completed. Contact the site administrator if this problem persists.".
How can I register there?

Thanks,
Łukasz

**Comment by julianoes** [comment]
The Yuneec SDK is very much unsupported as far as I know.

I suggest to use https://github.com/mavlink/MAVSDK-Java instead.

**Comment by luk77** [comment]
Thank you, good to know.
In fact I don't actualy need to use android or any other mobile system.
For the purpose of my project I have to control the Yuneec H520 drone from PC (windows). I was trying to use Android SDK because as far as I know there is no "direct" windows API for H520. But if MAVSDK could be used to communicate with H520 I prefer C++/C# version.

Could you please confirm if it is possible to control H520 using MAVSDK directly from Windows?

Also, if you could reccomend any place where I could find more information about such integration I would be very grateful.

Thanks.

**Comment by julianoes** [comment]
> Could you please confirm if it is possible to control H520 using MAVSDK directly from Windows?

Yes that should work.

**Comment by luk77** [comment]
Thanks @julianoes for your suggestion, I can confirm that MAVSDK can be used for communication with Yuneec H520. I tested python version of this library and I am able to control gimbal, arm/disarm the drone, etc. directly from python script.

Howewer, I also identified one problem with this solution. I am able to control the drone from python script only when the GCS is turned off. If I start GCS ST16S and it connects, python scripts do not work anymore. For my project I need GCS to be fully functional, so I need both things (GCS and application with MAVSDK) to work at the same time. I think the old android API for Yuneec H520 worked exactly this way - I remember I was able to control gimbal from GCS and from Android API at the same time.

I think the reason of this issue in my current approach is that I use port 14550 to connect to drone. I believe that ST16S use the same port, and here is the conflict.

Currently I use this python code to connect to drone:
`await drone.connect(system_address="udp://:14550")`

So my questions are:
1. how to setup the communication with drone to use GCS and MAVLINK application at the same time?
2. does Yuneec H520 expose any other ports I could use for communication over MAVSDK?

Thanks in advance for any help.

**Comment by julianoes** [comment]
I don't remember exactly anymore, sorry. Try connecting on 14540 instead. If that doesn't work, use wireshark to see if there are heartbeats sent on some other port.

**Comment by luk77** [comment]
Thanks again for the suggestions. I analyzed the messages sent from the drone using Wireshark.
For others interested in this topic: The Yuneec H520 provides three ports for connection: 14530, 14540, 14550. It seems the GCS uses 14550, so to avoid conflict when connecting using mavsdk it is better to use port 14540 or 14530.

**Comment by julianoes** [comment]
Great, thanks for the note!
